import { useState } from 'react';
import { createPortal } from 'react-dom';
import { X, Plus, Minus, ShoppingCart, Ruler } from 'lucide-react';
import { AnimatePresence, motion } from 'framer-motion';
import SizeGuideModal from './SizeGuideModal';

export default function QuickViewModal({ product, onClose, onAddToCart }) {
    const [selectedSize, setSelectedSize] = useState(product?.sizes?.[0] || null);
      const [quantity, setQuantity] = useState(1);
        const [sizeGuideOpen, setSizeGuideOpen] = useState(false);
          const [added, setAdded] = useState(false);

            if (!product) return null;

              const handleAdd = () => {
                    for (let i = 0; i < quantity; i++) {
                            onAddToCart(product, selectedSize);
                    }
                        setAdded(true);
                            setTimeout(() => { setAdded(false); onClose(); }, 1200);
              };

                const modalContent = (
                      <>
                            <AnimatePresence>
                                    <motion.div
                                              initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
                                                        onClick={onClose}
                                                                  className="fixed inset-0 z-[9998] bg-black/75 backdrop-blur-sm"
                                                                          />
                                                                                  <motion.div
                                                                                            initial={{ opacity: 0, scale: 0.95, y: 24 }}
                                                                                                      animate={{ opacity: 1, scale: 1, y: 0 }}
                                                                                                                exit={{ opacity: 0, scale: 0.95, y: 24 }}
                                                                                                                          transition={{ duration: 0.25 }}
                                                                                                                                    className="fixed z-[9999] top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[calc(100vw-2rem)] max-w-2xl max-h-[90vh] overflow-y-auto bg-[#0f0f12] border border-cream/10 rounded-sm shadow-2xl"
                                                                                                                                            >
                                                                                                                                                      <button
                                                                                                                                                                  onClick={onClose}
                                                                                                                                                                              className="absolute top-4 right-4 z-10 text-cream/30 hover:text-cream rounded-sm p-1"
                                                                                                                                                                                        >
                                                                                                                                                                                                    <X className="w-5 h-5" />
                                                                                                                                                                                                              </button>

                                                                                                                                                                                                                        <div className="flex flex-col sm:flex-row">
                                                                                                                                                                                                                                    {/* Image */}
                                                                                                                                                                                                                                                <div className="sm:w-1/2 h-64 sm:h-auto bg-white/[0.03] flex items-center justify-center overflow-hidden">
                                                                                                                                                                                                                                                              {product.image ? (
                                                                                                                                                                                                                                                                                <img
                                                                                                                                                                                                                                                                                                  src={product.image}
                                                                                                                                                                                                                                                                                                                    alt={product.name}
                                                                                                                                                                                                                                                                                                                                      className="w-full h-full object-contain object-center"
                                                                                                                                                                                                                                                                                                                                                        style={{ maxHeight: '400px' }}
                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                              ) : (
                                                                                                                                                                                                                                                                                <div className="w-full h-full flex items-center justify-center bg-white/5">
                                                                                                                                                                                                                                                                                                  <span className="text-cream/30 text-sm">No image</span>
                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                      {/* Details */}
                                                                                                                                                                                                                                                                                                  <div className="sm:w-1/2 p-6 flex flex-col gap-4">
                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                <p className="text-xs uppercase tracking-widest text-gold font-barlow-condensed mb-1">{product.category}</p>
                                                                                                                                                                                                                                                                                                                                                <h2 className="text-xl font-barlow-condensed font-bold text-cream leading-tight">{product.name}</h2>
                                                                                                                                                                                                                                                                                                                                                                <p className="text-2xl font-bold text-gold mt-1">${product.price}</p>
                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-cream/60 text-sm leading-relaxed">{product.description}</p>

                                                                                                                                                                                                                                                                                                                                                                                                          {/* Size */}
                                                                                                                                                                                                                                                                                                                                                                                                                        {product.sizes && product.sizes.length > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex items-center justify-between mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="text-xs uppercase tracking-widest text-cream/50 font-barlow-condensed">Size</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={() => setSizeGuideOpen(true)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="text-xs text-gold/70 hover:text-gold flex items-center gap-1"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Ruler className="w-3 h-3" /> Size Guide
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex flex-wrap gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {product.sizes.map(size => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      key={size}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={() => setSelectedSize(size)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className={`px-3 py-1.5 text-xs font-barlow-condensed font-bold border rounded-sm transition-all ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  selectedSize === size
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ? 'bg-gold text-ink border-gold'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          : 'bg-transparent text-cream/50 border-cream/20 hover:border-cream/50'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {size}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                        )}

                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Quantity */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="flex items-center gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="text-xs uppercase tracking-widest text-cream/50 font-barlow-condensed">Qty</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="flex items-center border border-cream/20 rounded-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button onClick={() => setQuantity(q => Math.max(1, q - 1))} className="px-2 py-1 text-cream/50 hover:text-cream">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Minus className="w-3 h-3" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="px-3 text-sm text-cream">{quantity}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button onClick={() => setQuantity(q => q + 1)} className="px-2 py-1 text-cream/50 hover:text-cream">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Plus className="w-3 h-3" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={handleAdd}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className={`mt-auto w-full py-3.5 font-barlow-condensed font-bold ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      added
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ? 'bg-green-500/20 border border-green-500/40 text-green-400'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              : 'bg-gold hover:bg-gold-dark text-ink hover:shadow-lg hover:shadow-gold/20'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <ShoppingCart className="w-4 h-4" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {added ? '✓ Added to Cart!' : 'Add to Cart'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </AnimatePresence>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <SizeGuideModal open={sizeGuideOpen} onClose={() => setSizeGuideOpen(false)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </>
                );

                  return createPortal(modalContent, document.body);
}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  